---
- name: Create elk configuration files
  template:
    dest: "{{ ELK_ROOT_LOCATION }}/configs/{{ item }}.yml"
    src: "configs/{{ item }}.yml.j2"
    mode: 0755
    owner: root
  with_items: "{{ ELK_SERVICES }}"

- name: Create logstash patterns configuration files
  template:
    src: "{{ item }}"
    dest: "{{ ELK_ROOT_LOCATION }}/logstash_pipelines/{{ item | basename | regex_replace('.j2','') }}"
    mode: 0755
  notify: restart logstash
  with_fileglob:
    - templates/logstash_pipelines/*.j2

- name: Create logstash patterns configuration files
  template:
    src: "{{ item }}"
    dest: "{{ ELK_ROOT_LOCATION }}/logstash_patterns/{{ item | basename | regex_replace('.j2','') }}"
    mode: 0755
  notify: restart logstash
  with_fileglob:
    - templates/logstash_patterns/*.j2
