---
- name: Create ELK files directories
  file:
    path: "{{ item }}"
    mode: 0755
    owner: root
    recurse: true
    state: directory
  with_items:
    - "{{ ELK_ROOT_LOCATION }}"
    - "{{ ELK_ROOT_LOCATION }}/configs"
    - "{{ ELK_ROOT_LOCATION }}/dockerfiles"
    - "{{ ELK_ROOT_LOCATION }}/logs"
    - "{{ ELK_ROOT_LOCATION }}/logstash_patterns"
    - "{{ ELK_ROOT_LOCATION }}/logstash_pipelines"
    - "{{ ELK_ROOT_LOCATION }}/ssl"

- name: Build docker images
  include: build_images.yml

- name: Install elk configurations.
  include: config.yml

- name: Create services containers
  include: services.yml
