---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'
    - name: Apply dependancies
      include_role:
        name: lucasmaurice.ansible_role_docker

  roles:
    - role: elk
